---
title: "Modeling Preference Heterogeneity"
output: github_document
---

## Abstract

We examine two data sources for informing the upper-level model of heterogeneity in a conjoint study about car purchase. The first is stated brand preferences via traditional rating scales in the survey. The second is passive observational data on visits to car dealerships by brand. Both of these measures will come from a sample of 1,000 Dynata panelists who have agreed to be passively tracked and are in the market for a new or used vehicle in the next six months.

## Project Organization

- `/Code` Scripts with prefixes (e.g., `01_import-data.R`, `02_clean-data.R`) and functions in `/Source`.
- `/Data` Simulated and real data, the latter not pushed.
- `/Figures` PNG images and plots.
- `/Output` Output from model runs, not pushed.
- `/Presentation` Presentation slides, without its knitted PDF pushed.
- `/Private` A catch-all folder for miscellaneous files, not pushed.
- `/Writing` Case studies and the paper, without its knitted PDF pushed.

For general details on collaborating using GitHub see [Research Assistant Training](https://github.com/marcdotson/ra-training).
